import { useEffect, useRef, useState, type CSSProperties } from "react";
import { useCitySim } from "../hooks/useCitySim";
import { initSpeechVoices, stopAllSpeech } from "../speech/characterSpeech";
import { HUMAN_ENTITY_ID } from "../data/townCharacters";

/**
 * Rolling chat + optional player typing. NPC speech is logged from ConversationSystem
 * and spoken via Edge TTS (dev server `/api/edge-tts`) with Web Speech fallback.
 */
export default function DialogueChatPanel() {
  const { manager, simVersion, bump } = useCitySim();
  const scrollRef = useRef<HTMLDivElement>(null);
  const lines = manager.dialogueLog;
  const [draft, setDraft] = useState("");
  const [orderHint, setOrderHint] = useState<string | null>(null);
  const [chatHint, setChatHint] = useState<string | null>(null);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    initSpeechVoices();
  }, []);

  useEffect(() => {
    const el = scrollRef.current;
    if (el) el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
  }, [simVersion, lines.length]);

  const submit = async () => {
    const t = draft.trim();
    if (!t) return;
    setSending(true);
    setChatHint(null);
    setDraft("");
    const res = await manager.submitPlayerChat(HUMAN_ENTITY_ID, t);
    if (!res.ok) {
      const map: Record<string, string> = {
        empty: "Type something first.",
        no_player: "No active player resident in simulation.",
        no_npc_nearby: "No NPC nearby. Walk close to someone before chatting.",
      };
      setChatHint(map[res.reason ?? ""] ?? "Could not send chat.");
    }
    setSending(false);
  };

  const tryBurgerOrder = () => {
    setOrderHint(null);
    const r = manager.tryPlayerPlaceBurgerOrder();
    if (r.ok) {
      setOrderHint(
        r.kind === "queued" ? "In line — Maya will take it when free." : "Order sent to the window."
      );
    } else {
      const map: Record<NonNullable<typeof r.reason>, string> = {
        inactive:
          "Burger service off — place the joint markers in layout, relaunch sim.",
        too_far: "Walk to the burger order marker (see layout).",
        no_cash: "Not enough money for a classic burger.",
        no_human: "No player entity in sim.",
      };
      setOrderHint(map[r.reason] ?? "Can't order right now.");
    }
    bump();
  };

  return (
    <div
      style={{
        height: "100%",
        display: "flex",
        flexDirection: "column",
        fontFamily: "system-ui, Segoe UI, sans-serif",
        fontSize: 12,
        lineHeight: 1.35,
        color: "#e4e4ec",
        background: "rgba(8,10,18,0.92)",
        border: "1px solid rgba(255,255,255,0.12)",
        borderRadius: 10,
        padding: "10px 12px",
        minHeight: 0,
      }}
    >
      <div
        style={{
          fontWeight: 700,
          marginBottom: 6,
          color: "#86efac",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <span>Town chat</span>
        <button
          type="button"
          onClick={() => stopAllSpeech()}
          style={btnSmall}
          title="Stop speech"
        >
          Stop TTS
        </button>
      </div>

      <p style={{ margin: "0 0 6px", fontSize: 10, color: "#9ca3af" }}>
        Walk near an NPC and send a line. Replies are generated by the host AI pipeline.
      </p>
      {chatHint ? (
        <div style={{ marginBottom: 6, fontSize: 10, color: "#fca5a5" }}>{chatHint}</div>
      ) : null}
      {manager.simulationEnabled && manager.getHuman() ? (
        <div
          style={{
            marginBottom: 8,
            padding: "6px 8px",
            borderRadius: 6,
            background: "rgba(20,30,12,0.5)",
            border: "1px solid rgba(120,180,80,0.2)",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              gap: 6,
            }}
          >
            <span style={{ fontSize: 10, color: "#a3e635" }}>
              Cash: ${manager.getHuman()!.money.toFixed(0)}
            </span>
            <button
              type="button"
              onClick={tryBurgerOrder}
              style={btnBurger}
              title="Place order at the burger order marker (stand in range)"
            >
              Order classic burger
            </button>
          </div>
          {orderHint ? (
            <div style={{ fontSize: 9, color: "#c6d4a8", marginTop: 4 }}>{orderHint}</div>
          ) : null}
        </div>
      ) : null}

      <div
        ref={scrollRef}
        style={{
          flex: 1,
          minHeight: 80,
          overflowY: "auto",
          paddingRight: 4,
          borderTop: "1px solid rgba(255,255,255,0.06)",
          paddingTop: 8,
        }}
      >
        {lines.length === 0 ? (
          <div style={{ color: "#6b7280", fontStyle: "italic" }}>
            No dialogue yet. Relaunch sim and bump into townspeople.
          </div>
        ) : (
          lines.map((line) => {
            const isYou = line.speakerId === HUMAN_ENTITY_ID;
            return (
              <div
                key={line.id}
                style={{
                  marginBottom: 10,
                  paddingBottom: 8,
                  borderBottom: "1px solid rgba(255,255,255,0.05)",
                }}
              >
                <div
                  style={{
                    color: isYou ? "#93c5fd" : "#c4b5fd",
                    fontWeight: 600,
                    fontSize: 11,
                  }}
                >
                  {line.speakerName}
                </div>
                <div style={{ color: "#e8e8ef", marginTop: 2 }}>{line.text}</div>
              </div>
            );
          })
        )}
      </div>

      <div style={{ marginTop: 8, display: "flex", gap: 6 }}>
        <input
          type="text"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") void submit();
          }}
          placeholder="Type a line as your resident…"
          style={inputStyle}
        />
        <button type="button" onClick={() => void submit()} style={btnSend} disabled={sending}>
          {sending ? "..." : "Send"}
        </button>
      </div>
    </div>
  );
}

const btnBurger: CSSProperties = {
  fontSize: 10,
  padding: "4px 8px",
  borderRadius: 6,
  border: "1px solid rgba(163,230,53,0.45)",
  background: "rgba(60,80,20,0.5)",
  color: "#ecfccb",
  cursor: "pointer",
  whiteSpace: "nowrap",
};

const btnSmall: CSSProperties = {
  fontSize: 10,
  padding: "3px 8px",
  borderRadius: 6,
  border: "1px solid rgba(255,255,255,0.15)",
  background: "rgba(255,255,255,0.06)",
  color: "#cbd5e1",
  cursor: "pointer",
};

const btnSend: CSSProperties = {
  ...btnSmall,
  padding: "6px 10px",
  background: "rgba(34,197,94,0.25)",
  borderColor: "rgba(74,222,128,0.35)",
};

const inputStyle: CSSProperties = {
  flex: 1,
  minWidth: 0,
  padding: "6px 8px",
  borderRadius: 6,
  border: "1px solid rgba(255,255,255,0.12)",
  background: "rgba(0,0,0,0.35)",
  color: "#f3f4f6",
  fontSize: 12,
};
